
build_executable:
  stage: build
  image: python:3.7

  script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install -U pyinstaller
    - pyinstaller \
      --add-data spectra_compiler/app.py \
      --add-data spectra_compiler/generator.py \
      --add-data spectra_compiler/utils.py \
      --add-data spectra_compiler/workers.py \
      spectra_compiler/main.py

  artifacts:
    paths:
      - build/
      - dist/
