
build_executable_linux:
  stage: build
  image: python:3.11

  script:
    # Install requirements for seabreeze, see https://python-seabreeze.readthedocs.io/en/latest/install.html
    - apt-get install git-all build-essential libusb-dev
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install -U pyinstaller
    - pyinstaller --icon resources/rainbow.ico --onefile main.py

  artifacts:
    paths:
      - build/
      - dist/

build_executable_windows:
  stage: build
  image: python:3.11

  tags:
    - windows

  script:
    # Install Chocolatey
    - Get-ExecutionPolicy
    - Set-ExecutionPolicy Bypass -Scope Process -Force
    - "[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))"
    # Update chocolatey
    - choco upgrade chocolatey
    # Install requirements for seabreeze
    - choco install visualcpp-build-tools
    - choco install windows-sdk-10.1
    - choco install windowsdriverkit10
    # Updating pip
    - C:\Python\python.exe -m pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install -U pyinstaller
    - pyinstaller --icon resources/rainbow.ico --onefile main.py

  artifacts:
  paths:
    - build/
    - dist/