
build_executable:
  stage: build
  image: python:3.7

  script:
    - pip install --upgrade pip
    - pip install -U pyinstaller
    - pyinstaller spectra-compiler/main.py

  artifacts:
    paths:
      - build/
      - dist/
