
build_executable_linux:
  stage: build
  image: python:3.11

  script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install -U pyinstaller
    - pyinstaller --icon resources/rainbow.ico --onefile main.py

  artifacts:
    paths:
      - build/
      - dist/

build_executable_windows:
  stage: build
  image: python:3.11

  tags:
    - windows

  script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install -U pyinstaller
    - pyinstaller --icon resources/rainbow.ico --onefile main.py