
build_executable:
  stage: build
  image: python:3.7

  script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install -U pyinstaller
    - pyinstaller spectra_compiler

  artifacts:
    paths:
      - build/
      - dist/
